# Generated by Django 5.2.4 on 2025-07-17 21:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_picture', models.ImageField(blank=True, default='khetmah/images/profile_pictures/default.png', null=True, upload_to='khetmah/images/profile_pictures/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Khetmah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('completed', 'مكتملة'), ('archived', 'مؤرشفة'), ('canceled', 'ملغاة')], default='active', max_length=20)),
                ('reason', models.CharField(blank=True, choices=[('dead', 'هبة لمتوفي'), ('need', 'لطلب حاجة'), ('sick', 'لطلب شفاء'), ('travel', 'السفر'), ('Thank_God', 'شكر لله'), ('days', 'أيام فضيلة'), ('other', 'سبب آخر')], default='Thank_God', max_length=20, null=True)),
                ('sharing_type', models.CharField(blank=True, choices=[('family_friends', 'مع الأهل والأصدقاء'), ('public', 'عامة للجميع')], default='family_friends', max_length=20, null=True)),
                ('na3wa_image', models.ImageField(blank=True, default='khetmah/images/na3wa_pictures/not-available.png', null=True, upload_to='khetmah/images/na3wa_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deceased_name', models.CharField(blank=True, max_length=32, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('specific_reason', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_khetmah', to=settings.AUTH_USER_MODEL)),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite_khetmahs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('khetmah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='khetmah_comments', to='khetmah.khetmah')),
            ],
        ),
        migrations.CreateModel(
            name='Juza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juz_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('available', 'متاح'), ('taken', 'محجوز'), ('read', 'مقروء')], default='available', max_length=10)),
                ('taked_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_selected_juza', to=settings.AUTH_USER_MODEL)),
                ('khetmah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juz_selections', to='khetmah.khetmah')),
            ],
            options={
                'unique_together': {('khetmah', 'juz_number')},
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('khetmah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='khetmah.khetmah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'khetmah')},
            },
        ),
    ]
