# Generated by Django 5.2.4 on 2025-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khetmah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khetmah',
            name='status',
            field=models.CharField(choices=[('active', 'نشطة'), ('completed', 'مكتملة'), ('archived', 'مؤرشفة')], default='active', max_length=20),
        ),
    ]
