# Generated by Django 5.2.4 on 2026-04-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khetmah', '0002_alter_khetmah_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khetmah',
            name='favorite',
        ),
    ]
