# Generated by Django 5.2.4 on 2026-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khetmah', '0003_remove_khetmah_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juza',
            name='taked_at',
        ),
        migrations.AddField(
            model_name='juza',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
