# Generated by Django 5.2.4 on 2026-04-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khetmah', '0004_remove_juza_taked_at_juza_taken_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
