# Generated by Django 5.2.4 on 2026-05-19 17:58

import django.db.models.deletion
import khetmah.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khetmah', '0005_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juza',
            name='khetmah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='khetmah.khetmah'),
        ),
        migrations.AlterField(
            model_name='khetmah',
            name='na3wa_image',
            field=models.ImageField(blank=True, null=True, upload_to=khetmah.models.na3wa_upload_path),
        ),
    ]
