# Generated by Django 5.2.4 on 2026-05-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khetmah', '0006_alter_juza_khetmah_alter_khetmah_na3wa_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
