# Generated by Django 5.2.4 on 2026-05-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khetmah', '0009_alter_khetmah_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khetmah',
            name='status',
            field=models.CharField(choices=[('active', 'نشطة'), ('completed', 'مكتملة')], default='active', max_length=20),
        ),
    ]
